[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool]
python_version = "3.9"

[project]
name = "my-project"
version = "1.0.0"
description = "My awesome project"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"